export const COMMERCIAL_RULE_DEFAULTS = {
  inactive_days: 21,
  volume_drop_pct: 35,
  min_margin_pct: 0.12,
  target_margin_pct: 0.2,
  max_days_without_prospect_followup: 7,
  max_days_without_quote_followup: 5,
  strategic_amount_min: 5000,
  strategic_volume_min: 1000,
  late_days_alert: 15,
  late_days_block: 30,
  claim_threshold: 3,
}

export const COMMERCIAL_CATALOG_DEFAULTS = {
  channels: ['HORECA', 'Particular', 'Retail', 'Distribuidores', 'Tiendas'],
  customerTypes: ['Mayorista', 'Retail', 'Institucional', 'HoReCa', 'Exportacion'],
  prospectStates: ['Nuevo', 'Contactado', 'Interesado', 'Cotizacion enviada', 'Negociacion', 'Prueba de producto', 'Aprobado', 'Convertido a cliente', 'Perdido', 'Sin respuesta', 'Pausado'],
  leadSources: ['Recomendacion', 'WhatsApp', 'Feria', 'Web', 'Vendedor', 'Cliente actual'],
  followupTypes: ['Llamada', 'WhatsApp', 'Correo', 'Visita', 'Reunion', 'Envio de muestra', 'Seguimiento de cotizacion', 'Seguimiento de pago', 'Reclamo', 'Renovacion de precio', 'Reactivacion de cliente', 'Otro'],
  lossReasons: ['Precio', 'Sin respuesta', 'Sin presupuesto', 'Competencia', 'No califica', 'Logistica'],
  alertTypes: ['Cliente inactivo', 'Caida de volumen', 'Margen bajo', 'Rentabilidad negativa', 'Mora alta', 'Prospecto sin seguimiento', 'Cotizacion sin seguimiento'],
  priorities: ['Baja', 'Media', 'Alta', 'Urgente'],
  segments: ['AAA', 'AA', 'A', 'B', 'C', 'Estrategico'],
}

export const COMMERCIAL_PERMISSIONS_DEFAULTS = {
  Admin: ['*'],
  Gerencia: ['dashboard', 'prospects', 'followups', 'profitability', 'intelligence', 'settings'],
  Comercial: ['dashboard', 'prospects', 'followups', 'intelligence'],
  Vendedor: ['dashboard', 'prospects', 'followups'],
  Cobros: ['dashboard', 'intelligence'],
  Logistica: ['dashboard', 'intelligence'],
  'Solo lectura': ['dashboard'],
}

export const mockProspects = [
  {
    id: 'mock-prospect-1',
    commercial_name: 'Supermercados El Roble',
    legal_name: 'El Roble, S.A.',
    contact_name: 'Andrea Figueroa',
    contact_role: 'Compras',
    phone: '5551-0001',
    whatsapp: '5551-0001',
    email: 'andrea@elroble.com',
    commercial_address: 'Zona 10, Ciudad de Guatemala',
    zone: 'Zona 10',
    channel: 'Retail',
    business_type: 'Supermercado',
    lead_source: 'Recomendacion',
    interest_category: 'Hojas frescas',
    estimated_volume: 120,
    estimated_monthly_potential: 8500,
    closing_probability: 72,
    status: 'negociacion',
    first_contact_date: '2026-04-10',
    last_contact_at: '2026-04-26T10:30:00Z',
    next_followup_at: '2026-04-29T16:00:00Z',
    observations: 'Interes en surtido premium y entrega 3 veces por semana.',
    salesperson_name: 'Luis Paredes',
    responsible_id: null,
  },
  {
    id: 'mock-prospect-2',
    commercial_name: 'Bistro Urbano',
    legal_name: '',
    contact_name: 'Mario Estrada',
    contact_role: 'Chef ejecutivo',
    phone: '5551-0002',
    whatsapp: '5551-0002',
    email: 'chef@bistrourbano.gt',
    commercial_address: 'Zona 14',
    zone: 'Zona 14',
    channel: 'HORECA',
    business_type: 'Restaurante',
    lead_source: 'WhatsApp',
    interest_category: 'Microgreens',
    estimated_volume: 40,
    estimated_monthly_potential: 3200,
    closing_probability: 54,
    status: 'prueba_producto',
    first_contact_date: '2026-04-12',
    last_contact_at: '2026-04-27T14:00:00Z',
    next_followup_at: '2026-04-30T15:00:00Z',
    observations: 'Pide muestra de arugula y brotes mixtos.',
    salesperson_name: 'Luis Paredes',
    responsible_id: null,
  },
]

export const mockFollowups = [
  {
    id: 'mock-followup-1',
    related_name: 'Supermercados El Roble',
    related_type: 'prospecto',
    followup_type: 'Visita',
    responsible_name: 'Luis Paredes',
    scheduled_at: '2026-04-29T16:00:00Z',
    priority: 'alta',
    status: 'pendiente',
    notes: 'Revisar condiciones de anaquel y pedido minimo.',
    next_action: 'Enviar propuesta revisada',
  },
  {
    id: 'mock-followup-2',
    related_name: 'Cliente San Lucas',
    related_type: 'cliente',
    followup_type: 'Seguimiento de pago',
    responsible_name: 'Cobros central',
    scheduled_at: '2026-04-28T13:00:00Z',
    priority: 'urgente',
    status: 'vencido',
    notes: 'Factura 001-230 vence hoy.',
    next_action: 'Confirmar promesa de pago',
  },
]

export const mockAlerts = [
  {
    id: 'mock-alert-1',
    alert_type: 'Cliente inactivo',
    severity: 'alta',
    status: 'nueva',
    title: 'Cliente El Encinal no compra desde hace 24 dias',
    description: 'El cliente lleva mas dias que el limite configurado sin registrar pedidos.',
    recommended_action: 'Programar visita comercial',
    related_name: 'El Encinal',
    responsible_name: 'Luis Paredes',
    detected_at: '2026-04-28T09:00:00Z',
  },
  {
    id: 'mock-alert-2',
    alert_type: 'Margen bajo',
    severity: 'media',
    status: 'en_revision',
    title: 'Cliente Bistro Urbano por debajo del margen objetivo',
    description: 'El margen neto estimado del ultimo mes esta 4.2 puntos debajo del objetivo.',
    recommended_action: 'Revisar lista de precios y frecuencia de entrega',
    related_name: 'Bistro Urbano',
    responsible_name: 'Luis Paredes',
    detected_at: '2026-04-27T16:30:00Z',
  },
]

export const mockProfitability = [
  {
    id: 'mock-profit-1',
    client_id: 'mock-client-1',
    client_name: 'Supermercados El Roble',
    channel: 'Retail',
    route_name: 'Ruta Centro',
    salesperson_name: 'Luis Paredes',
    net_sales: 25400,
    gross_sales: 26800,
    estimated_product_cost: 17780,
    estimated_logistics_cost: 1780,
    claim_cost: 0,
    gross_margin: 8620,
    net_margin: 6840,
    gross_margin_pct: 0.3216,
    net_margin_pct: 0.2693,
    avg_ticket: 4233,
    purchased_volume: 1840,
    purchase_frequency: 6,
    classification: 'Alto volumen / alto margen',
    recommendations: ['Mantener por valor estrategico', 'Evaluar cross sell de nuevos mixes'],
  },
  {
    id: 'mock-profit-2',
    client_id: 'mock-client-2',
    client_name: 'Bistro Urbano',
    channel: 'Foodservice',
    route_name: 'Ruta Capital',
    salesperson_name: 'Luis Paredes',
    net_sales: 6800,
    gross_sales: 7400,
    estimated_product_cost: 5040,
    estimated_logistics_cost: 980,
    claim_cost: 180,
    gross_margin: 2360,
    net_margin: 1200,
    gross_margin_pct: 0.3189,
    net_margin_pct: 0.1764,
    avg_ticket: 1700,
    purchased_volume: 360,
    purchase_frequency: 4,
    classification: 'Bajo volumen / alto margen',
    recommendations: ['Sugerir visita comercial', 'Consolidar entregas para bajar costo logistico'],
  },
]
