create table if not exists public.logistics_settings (
  id uuid not null default gen_random_uuid(),
  organization_id uuid not null,
  plant_name text,
  plant_address text,
  plant_latitude numeric(10,7),
  plant_longitude numeric(10,7),
  default_currency text not null default 'GTQ',
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint logistics_settings_pkey primary key (id),
  constraint logistics_settings_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade,
  constraint logistics_settings_created_by_fkey foreign key (created_by) references public.profiles(id)
);

create unique index if not exists idx_logistics_settings_org_unique
  on public.logistics_settings (organization_id);

create table if not exists public.vehiculos (
  id uuid not null default gen_random_uuid(),
  organization_id uuid not null,
  code text,
  name text not null,
  plate text not null,
  fuel_type text not null
    check (fuel_type in ('diesel', 'gasolina_regular', 'gasolina_super')),
  fuel_efficiency_km_per_gallon numeric not null default 0
    check (fuel_efficiency_km_per_gallon > 0),
  tank_capacity_gallons numeric,
  is_active boolean not null default true,
  notes text,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vehiculos_pkey primary key (id),
  constraint vehiculos_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade,
  constraint vehiculos_created_by_fkey foreign key (created_by) references public.profiles(id)
);

create unique index if not exists idx_vehiculos_org_plate_unique
  on public.vehiculos (organization_id, plate);

create index if not exists idx_vehiculos_org_active
  on public.vehiculos (organization_id, is_active, name);

create table if not exists public.historial_combustible (
  id uuid not null default gen_random_uuid(),
  organization_id uuid not null,
  fuel_type text not null
    check (fuel_type in ('diesel', 'gasolina_regular', 'gasolina_super')),
  price_per_gallon numeric not null default 0
    check (price_per_gallon > 0),
  effective_date date not null default current_date,
  notes text,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint historial_combustible_pkey primary key (id),
  constraint historial_combustible_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade,
  constraint historial_combustible_created_by_fkey foreign key (created_by) references public.profiles(id)
);

create index if not exists idx_historial_combustible_org_type_date
  on public.historial_combustible (organization_id, fuel_type, effective_date desc, created_at desc);

create table if not exists public.rutas (
  id uuid not null default gen_random_uuid(),
  organization_id uuid not null,
  route_number bigint generated by default as identity,
  route_name text,
  route_date date not null default current_date,
  vehicle_id uuid not null,
  driver_name text,
  driver_phone text,
  status text not null default 'planificada'
    check (status in ('planificada', 'en_ruta', 'finalizada', 'cancelada')),
  current_stop_sequence integer not null default 0,
  started_at timestamptz,
  finished_at timestamptz,
  plant_name_snapshot text,
  plant_address_snapshot text,
  plant_latitude numeric(10,7),
  plant_longitude numeric(10,7),
  notes text,
  total_orders integer not null default 0,
  total_distance_km numeric not null default 0,
  total_duration_minutes numeric not null default 0,
  total_segment_cost numeric not null default 0,
  total_extra_fuel_cost numeric not null default 0,
  total_route_cost numeric not null default 0,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint rutas_pkey primary key (id),
  constraint rutas_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade,
  constraint rutas_vehicle_id_fkey foreign key (vehicle_id) references public.vehiculos(id),
  constraint rutas_created_by_fkey foreign key (created_by) references public.profiles(id)
);

create unique index if not exists idx_rutas_org_route_number
  on public.rutas (organization_id, route_number);

create index if not exists idx_rutas_org_status_date
  on public.rutas (organization_id, status, route_date desc, created_at desc);

create table if not exists public.ruta_pedidos (
  id uuid not null default gen_random_uuid(),
  organization_id uuid not null,
  ruta_id uuid not null,
  order_id uuid not null,
  client_id uuid,
  sequence_no integer not null check (sequence_no > 0),
  status text not null default 'pendiente'
    check (status in ('pendiente', 'en_camino', 'entregado', 'parcial', 'omitido')),
  client_name_snapshot text not null,
  delivery_address_snapshot text not null,
  delivery_latitude numeric(10,7),
  delivery_longitude numeric(10,7),
  order_total_snapshot numeric not null default 0,
  delivery_photo_url text,
  delivery_notes text,
  dispatched_at timestamptz,
  delivered_at timestamptz,
  allocated_initial_cost numeric not null default 0,
  allocated_return_cost numeric not null default 0,
  allocated_progressive_cost numeric not null default 0,
  allocated_extra_fuel_cost numeric not null default 0,
  allocated_total_cost numeric not null default 0,
  margin_amount numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ruta_pedidos_pkey primary key (id),
  constraint ruta_pedidos_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade,
  constraint ruta_pedidos_ruta_id_fkey foreign key (ruta_id) references public.rutas(id) on delete cascade,
  constraint ruta_pedidos_order_id_fkey foreign key (order_id) references public.orders(id) on delete restrict,
  constraint ruta_pedidos_client_id_fkey foreign key (client_id) references public.clients(id) on delete set null
);

create unique index if not exists idx_ruta_pedidos_ruta_order_unique
  on public.ruta_pedidos (ruta_id, order_id);

create unique index if not exists idx_ruta_pedidos_ruta_sequence_unique
  on public.ruta_pedidos (ruta_id, sequence_no);

create index if not exists idx_ruta_pedidos_org_status
  on public.ruta_pedidos (organization_id, status, sequence_no);

create table if not exists public.ruta_tramos (
  id uuid not null default gen_random_uuid(),
  organization_id uuid not null,
  ruta_id uuid not null,
  sequence_no integer not null check (sequence_no > 0),
  segment_kind text not null
    check (segment_kind in ('salida_planta', 'intercliente', 'retorno_planta')),
  generated_from_event text not null
    check (generated_from_event in ('inicio_ruta', 'despacho_cliente', 'retorno_ruta')),
  from_stop_type text not null check (from_stop_type in ('planta', 'cliente')),
  to_stop_type text not null check (to_stop_type in ('planta', 'cliente')),
  from_ruta_pedido_id uuid,
  to_ruta_pedido_id uuid,
  from_label text not null,
  to_label text not null,
  origin_address text,
  destination_address text,
  origin_latitude numeric(10,7),
  origin_longitude numeric(10,7),
  destination_latitude numeric(10,7),
  destination_longitude numeric(10,7),
  distance_meters integer not null default 0,
  duration_seconds integer not null default 0,
  distance_km numeric not null default 0,
  duration_minutes numeric not null default 0,
  fuel_price_per_gallon numeric not null default 0,
  vehicle_efficiency_km_per_gallon numeric not null default 0,
  estimated_gallons numeric not null default 0,
  segment_cost numeric not null default 0,
  google_maps_response jsonb,
  created_by uuid,
  created_at timestamptz not null default now(),
  constraint ruta_tramos_pkey primary key (id),
  constraint ruta_tramos_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade,
  constraint ruta_tramos_ruta_id_fkey foreign key (ruta_id) references public.rutas(id) on delete cascade,
  constraint ruta_tramos_from_ruta_pedido_id_fkey foreign key (from_ruta_pedido_id) references public.ruta_pedidos(id) on delete set null,
  constraint ruta_tramos_to_ruta_pedido_id_fkey foreign key (to_ruta_pedido_id) references public.ruta_pedidos(id) on delete set null,
  constraint ruta_tramos_created_by_fkey foreign key (created_by) references public.profiles(id)
);

create unique index if not exists idx_ruta_tramos_ruta_sequence_unique
  on public.ruta_tramos (ruta_id, sequence_no);

create index if not exists idx_ruta_tramos_org_ruta
  on public.ruta_tramos (organization_id, ruta_id, created_at);

create table if not exists public.ruta_incidencias (
  id uuid not null default gen_random_uuid(),
  organization_id uuid not null,
  ruta_id uuid not null,
  ruta_pedido_id uuid,
  incident_type text not null
    check (incident_type in ('cliente_ausente', 'rechazo_cliente', 'averia', 'trafico', 'documentacion', 'otra')),
  severity text not null default 'media'
    check (severity in ('baja', 'media', 'alta')),
  description text not null,
  support_file_url text,
  estimated_cost numeric not null default 0,
  occurred_at timestamptz not null default now(),
  created_by uuid,
  created_at timestamptz not null default now(),
  constraint ruta_incidencias_pkey primary key (id),
  constraint ruta_incidencias_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade,
  constraint ruta_incidencias_ruta_id_fkey foreign key (ruta_id) references public.rutas(id) on delete cascade,
  constraint ruta_incidencias_ruta_pedido_id_fkey foreign key (ruta_pedido_id) references public.ruta_pedidos(id) on delete set null,
  constraint ruta_incidencias_created_by_fkey foreign key (created_by) references public.profiles(id)
);

create index if not exists idx_ruta_incidencias_org_date
  on public.ruta_incidencias (organization_id, occurred_at desc, severity);

create table if not exists public.ruta_combustible_extra (
  id uuid not null default gen_random_uuid(),
  organization_id uuid not null,
  ruta_id uuid not null,
  fuel_date date not null default current_date,
  gallons numeric not null default 0 check (gallons > 0),
  unit_price numeric not null default 0 check (unit_price > 0),
  total_cost numeric not null default 0,
  reference_number text,
  support_file_url text,
  notes text,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ruta_combustible_extra_pkey primary key (id),
  constraint ruta_combustible_extra_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade,
  constraint ruta_combustible_extra_ruta_id_fkey foreign key (ruta_id) references public.rutas(id) on delete cascade,
  constraint ruta_combustible_extra_created_by_fkey foreign key (created_by) references public.profiles(id)
);

create index if not exists idx_ruta_combustible_extra_org_date
  on public.ruta_combustible_extra (organization_id, fuel_date desc, ruta_id);

drop trigger if exists trg_logistics_settings_updated_at on public.logistics_settings;
create trigger trg_logistics_settings_updated_at
before update on public.logistics_settings
for each row execute function public.set_updated_at();

drop trigger if exists trg_vehiculos_updated_at on public.vehiculos;
create trigger trg_vehiculos_updated_at
before update on public.vehiculos
for each row execute function public.set_updated_at();

drop trigger if exists trg_historial_combustible_updated_at on public.historial_combustible;
create trigger trg_historial_combustible_updated_at
before update on public.historial_combustible
for each row execute function public.set_updated_at();

drop trigger if exists trg_rutas_updated_at on public.rutas;
create trigger trg_rutas_updated_at
before update on public.rutas
for each row execute function public.set_updated_at();

drop trigger if exists trg_ruta_pedidos_updated_at on public.ruta_pedidos;
create trigger trg_ruta_pedidos_updated_at
before update on public.ruta_pedidos
for each row execute function public.set_updated_at();

drop trigger if exists trg_ruta_combustible_extra_updated_at on public.ruta_combustible_extra;
create trigger trg_ruta_combustible_extra_updated_at
before update on public.ruta_combustible_extra
for each row execute function public.set_updated_at();

alter table public.logistics_settings enable row level security;
alter table public.vehiculos enable row level security;
alter table public.historial_combustible enable row level security;
alter table public.rutas enable row level security;
alter table public.ruta_pedidos enable row level security;
alter table public.ruta_tramos enable row level security;
alter table public.ruta_incidencias enable row level security;
alter table public.ruta_combustible_extra enable row level security;

drop policy if exists logistics_settings_org_all on public.logistics_settings;
create policy logistics_settings_org_all on public.logistics_settings
using (organization_id = public.get_my_profile_org())
with check (organization_id = public.get_my_profile_org());

drop policy if exists vehiculos_org_all on public.vehiculos;
create policy vehiculos_org_all on public.vehiculos
using (organization_id = public.get_my_profile_org())
with check (organization_id = public.get_my_profile_org());

drop policy if exists historial_combustible_org_all on public.historial_combustible;
create policy historial_combustible_org_all on public.historial_combustible
using (organization_id = public.get_my_profile_org())
with check (organization_id = public.get_my_profile_org());

drop policy if exists rutas_org_all on public.rutas;
create policy rutas_org_all on public.rutas
using (organization_id = public.get_my_profile_org())
with check (organization_id = public.get_my_profile_org());

drop policy if exists ruta_pedidos_org_all on public.ruta_pedidos;
create policy ruta_pedidos_org_all on public.ruta_pedidos
using (organization_id = public.get_my_profile_org())
with check (organization_id = public.get_my_profile_org());

drop policy if exists ruta_tramos_org_all on public.ruta_tramos;
create policy ruta_tramos_org_all on public.ruta_tramos
using (organization_id = public.get_my_profile_org())
with check (organization_id = public.get_my_profile_org());

drop policy if exists ruta_incidencias_org_all on public.ruta_incidencias;
create policy ruta_incidencias_org_all on public.ruta_incidencias
using (organization_id = public.get_my_profile_org())
with check (organization_id = public.get_my_profile_org());

drop policy if exists ruta_combustible_extra_org_all on public.ruta_combustible_extra;
create policy ruta_combustible_extra_org_all on public.ruta_combustible_extra
using (organization_id = public.get_my_profile_org())
with check (organization_id = public.get_my_profile_org());

grant all on table public.logistics_settings to anon, authenticated, service_role;
grant all on table public.vehiculos to anon, authenticated, service_role;
grant all on table public.historial_combustible to anon, authenticated, service_role;
grant all on table public.rutas to anon, authenticated, service_role;
grant all on table public.ruta_pedidos to anon, authenticated, service_role;
grant all on table public.ruta_tramos to anon, authenticated, service_role;
grant all on table public.ruta_incidencias to anon, authenticated, service_role;
grant all on table public.ruta_combustible_extra to anon, authenticated, service_role;
grant all on sequence public.rutas_route_number_seq to anon, authenticated, service_role;

insert into storage.buckets (id, name, public)
values ('logistics-route-documents', 'logistics-route-documents', true)
on conflict (id) do nothing;

drop policy if exists logistics_route_documents_select_public on storage.objects;
create policy logistics_route_documents_select_public
on storage.objects
for select
to public
using (bucket_id = 'logistics-route-documents');

drop policy if exists logistics_route_documents_insert_auth on storage.objects;
create policy logistics_route_documents_insert_auth
on storage.objects
for insert
to authenticated
with check (bucket_id = 'logistics-route-documents');

drop policy if exists logistics_route_documents_update_auth on storage.objects;
create policy logistics_route_documents_update_auth
on storage.objects
for update
to authenticated
using (bucket_id = 'logistics-route-documents');
